"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

import { listSessionMessages, openAssistantReplyStream, postChatMessage } from "@/lib/api";
import type { ChatMessage } from "@/components/chat/types";

const WELCOME: ChatMessage = {
  role: "assistant",
  content:
    "Hi — upload a resume, paste a job description, or tell me your target role. Replies are generated by the worker after each message you send.",
};

export function useChat(sessionId: string | null, isOffline: boolean) {
  const [messages, setMessages] = useState<ChatMessage[]>([WELCOME]);
  const [isSending, setIsSending] = useState(false);

  useEffect(() => {
    if (!sessionId) {
      setMessages([WELCOME]);
      return;
    }
    if (isOffline) return;

    let cancelled = false;
    listSessionMessages(sessionId)
      .then((rows) => {
        if (cancelled) return;
        setMessages(rows.length > 0 ? rows : [WELCOME]);
      })
      .catch(() => {
        if (cancelled) return;
        setMessages([WELCOME]);
      });

    return () => {
      cancelled = true;
    };
  }, [sessionId, isOffline]);

  const canSend = useMemo(
    () => Boolean(sessionId) && !isOffline && !isSending,
    [sessionId, isOffline, isSending],
  );

  const sendMessage = useCallback(
    async (textRaw: string) => {
      const text = textRaw.trim();
      if (!text || !sessionId || isOffline || isSending) return;

      setIsSending(true);
      setMessages((prev) => [...prev, { role: "user", content: text }]);

      const streamRef: { current: EventSource | null } = { current: null };
      try {
        const userRow = await postChatMessage({ session_id: sessionId, message: text });

        await new Promise<void>((resolve, reject) => {
          streamRef.current = openAssistantReplyStream(sessionId, userRow.id, {
            onEvent: (ev) => {
              if (ev.type === "assistant") {
                setMessages((prev) => [...prev, { role: "assistant", content: ev.message.message }]);
                resolve();
                return;
              }
              if (ev.type === "timeout") {
                setMessages((prev) => [
                  ...prev,
                  {
                    role: "assistant",
                    content:
                      ev.detail ??
                      "No assistant reply yet — check that the worker is running, Redis is up, and OPENAI_API_KEY is set on the worker.",
                  },
                ]);
                resolve();
                return;
              }
              setMessages((prev) => [
                ...prev,
                {
                  role: "assistant",
                  content:
                    ev.detail === "user_message_not_found"
                      ? "That message was not found for this session."
                      : "Could not load the assistant reply. Check the API and try again.",
                },
              ]);
              resolve();
            },
            onTransportError: () => {
              reject(new Error("assistant_stream_failed"));
            },
          });
        });
      } catch {
        setMessages((prev) => [
          ...prev,
          {
            role: "assistant",
            content:
              "Could not send your message or open the reply stream. Check the API URL, CORS, and backend logs.",
          },
        ]);
      } finally {
        streamRef.current?.close();
        streamRef.current = null;
        setIsSending(false);
      }
    },
    [isOffline, isSending, sessionId],
  );

  return { messages, isSending, canSend, sendMessage };
}
