"""change main class to common class

Revision ID: 0008_change_main_class_to_common_class
Revises: 0007_resume_templates_uuid_pk
Create Date: 2026-04-07 20:59:25.342600

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0008_change_main_class_to_common_class'
down_revision = '0007_resume_templates_uuid_pk'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'updated_at')
    # ### end Alembic commands ###

